Dev
WildCodeSchool/paris-0921-p2-groupe2 pull request #13
Opened 2021-10-29 09:13 UTC by 110111-1

First sprint result 
functional app with one battle mode

2021-10-29 09:14 UTC, VincentCMLejeune submitted a review, later dismissed
All set and ready

2021-10-29 09:17 UTC, Charlotte-Men submitted a review, later dismissed
It's alive !

2021-10-29 09:17 UTC, isamj27950 submitted a review, later dismissed

2021-11-04 09:57 UTC, tyZulh requested changes
There is some changes to be made : 
-remove the dead code from your css
-check the import order in your components
-combine your fetch in one unique useEffect

To make  these changes  pull a new branches from dev

2021-11-04 09:57 UTC, tyZulh commented on src/Screens/Fighting results/DisplayFight.jsx
> +      .then((res) => res.json())
You can make one useEffect for both fetch

2021-11-04 15:49 UTC, pelegrand approved these changes
ok

2021-11-04 15:49 UTC, merged