Dev
WildCodeSchool/paris-0921-p2-groupe2 pull request #30
Opened 2021-11-16 09:08 UTC by Charlotte-Men

2021-11-16 09:18 UTC, VincentCMLejeune approved these changes

2021-11-17 08:36 UTC, pelegrand requested changes

2021-11-17 08:36 UTC, pelegrand commented on src/Screens/Menu/Menu3Modes.jsx
> +import FreeMode from '../../components/Accueil/FreeMode';
organiser les imports :

dépendences

components

styles

2021-11-17 08:36 UTC, pelegrand commented on src/components/Character detail/CharacterDetail.jsx
> +function CharacterDetail({ character }) {
Harmonisez vos components au niveau de l'export default

2021-11-17 11:31 UTC, closed without merging