Dev
WildCodeSchool/paris-0921-p2-groupe2 pull request #57
Opened 2021-11-18 16:36 UTC by isamj27950

2021-11-18 16:39 UTC, Charlotte-Men submitted a review, later dismissed
What a wonderful app !

2021-11-18 16:53 UTC, VincentCMLejeune approved these changes
I love it !

2021-11-18 20:12 UTC, pelegrand requested changes

2021-11-18 20:12 UTC, pelegrand commented on src/App.jsx
>  function App() {
Place the export default at the same place than the other files

2021-11-19 08:44 UTC, VincentCMLejeune approved these changes

2021-11-19 08:44 UTC, Charlotte-Men approved these changes

2021-11-19 10:01 UTC, pelegrand approved these changes

2021-11-19 10:01 UTC, merged